### ISSUE TITLE
R2 and L2 in Retroarch not working

### ISSUE THREAD

**Issue by reineckm** [retrogamecorps/s30-add-on-pack#1]
Hey awesome work! But on my device L2 and R2 in PSX doesn`t work.

In retroarch.cfg Line 1370 and 1403 those are not assigned so thats maybe the problem:

input_player1_l2 = "nul"
input_player1_r2 = "nul"

But I can't figure out what the right key is. The only way I know of testing keys is with ppsspp and locking in the controls.ini. There l2 and r2 correspond to the codes 1-105 and 1-104 but thats an dead end. 

Any Ideas?

**Comment by retrogamecorps** [comment]
So I just spent some time with it, and it appears that RetroArch as a whole doesn’t assign keys to L2 and R2.  If I go into the PC version of RetroArch they have the same keys assigned in there as for the PocketGo S30 — Z for “b”, X for “a”, etc — but nothing for L2 or R2.  So I think that even if we know the keycodes to the buttons (I do think that 105 and 104 are correct, based on what I am seeing in the input.conf file in the root folder of the SD card), it doesn’t actually register because you have to go into RetroArch and under Settings > Inputs > Player 1 Inputs to actually press the button and assigned it, and we’re locked out of RA like that.

I tried launching a game that uses L2/R2 (Spyro Year of the Dragon) and using different letters and key codes to see if I could get lucky, didn’t work.  I also tried running the PCSX4All emulator that comes with the SD card, but it shows “)" and “(" as the buttons for L2 and R2.  

I think I’m out of ideas, I’ll have to leave it as a “known issue” for now.

Russ

**Comment by deusxmach1na** [comment]
I don't know the answer here either, but I did get Dreamcast triggers working by changing `retroarch.cfg`.  

Changed these settings:
```
input_player1_l2 = "q"
input_player1_l2_axis = "q"
input_player1_l2_btn = "q"
...
input_player1_r2 = "w"
input_player1_r2_axis = "w"
input_player1_r2_btn = "w"
```

Is it possible to have one config per core, so at least the DC triggers will work?

Edit:
I should say, it made R1 and L1 work as the triggers.

**Comment by retrogamecorps** [comment]
Created a separate cfg file for Dreamcast and added this fix, thanks.  It still doesn't fix the L2/R2 issue in PS1, because I can't figure out what letters are assigned to those buttons.  Luckily keeping the PCSX4All emulator intact allows for L2/R2 and this emulator runs pretty well so it's not a huge loss.  Thanks again.

**Comment by retrogamecorps** [comment]
We have a full working RetroArch now so no need for these workarounds.  Everything is mapped appropriately.  It will be in my next release.  Closing!

**Comment by strouder** [comment]
This is still not fixed on the latest Retroarch. I'm using GamesirX2 and using PS1, Duckstation, this isn't mapped correctly... only L1 and R1 works.
