### ISSUE TITLE
Neo Geo Pocket Color State Issue

### ISSUE THREAD

**Issue by supertombrother** [retrogamecorps/s30-add-on-pack#20]
Every time I use a save state on the neo geo pocket color emulator, it changes which state slot the emulator uses. As a result, I cannot simply load a previous state, because the assigned slot changed right after the state was made. A full hotkeys list for every emulator would solve this and many other problems.

**Comment by retrogamecorps** [comment]
Swap out the emus/retro/retroarch-gb.cfg file in your SD card with the one found in this folder: https://github.com/retrogamecorps/s30-add-on-pack/tree/main/retro

That will fix the auto-indexing.  Might as well swap out the other cfg files too, because it sounds like you are using the cfg files from the v1.6 update, before I fixed that issue.

As far as hotkeys, I actually can't implement any right now due to the way that the factory configured RetroArch.  We've already put in a request with the factory to open up RA for us, and if they do it I can make a lot of extra changes for the device.
