### ISSUE TITLE
N64 analog stick not working

### ISSUE THREAD

**Issue by retrogamecorps** [retrogamecorps/s30-add-on-pack#21]
I would like to add N64, and I can get it to boot and run fine, but right now it's unplayable because I cannot get the analog stick to register.

https://drive.google.com/file/d/1NqLgp6d_aCcrQPUc1tciNeGo1zUernnU/view?usp=sharing

**Comment by Tapsi** [comment]
It's hard to support the N64 controller because L2/R2 doesn't work in RetroArch, right? I think most games use the D-Pad or analog stick, so as a workaround you could use the D-PAD as the analog stick in the config. However, the problems are the C buttons and the Z button.... because there are no buttons on the device that can do this job.

**Comment by deusxmach1na** [comment]
~~I can't seem to get past the N64 logo without it crashing, just those 2 files is all we need?~~

Edit: bad rom I guess.

**Comment by retrogamecorps** [comment]
N64 is now working, and will be in my next release.  Closing!
