### ISSUE TITLE
Games refuse to save.

### ISSUE THREAD

**Issue by supertombrother** [retrogamecorps/s30-add-on-pack#8]
After I added a bunch of games, the emulators wouldn't save progress anymore. This includes regular saves and save states. The original firmware lets me save, so why can't I save with your custom package?

**Comment by retrogamecorps** [comment]
Yes, unfortunately the saves are having an issue with the updated RetroArch cores I am using.  It has to do with the way the device powers down vs what RetroArch needs in order to lock in a save game.  I am hoping that another developer (who should be getting his unit any day now) will be able to make some changes to the firmware itself to fix this.

**Comment by retrogamecorps** [comment]
Safe shutdown is now available in the v1.7 add-on pack, just follow the instructions in my ReadMe file.  This will fix the saves issue.
